/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : canCom1.h
**     Project     : CAN_MASTER_Example
**     Processor   : S32K144_100
**     Component   : fsl_flexcan
**     Version     : Component S32K144_SDK01, Driver 01.00, CPU db: 3.00.000
**     Repository  : S32K144_SDK01
**     Compiler    : IAR ARM C Compiler
**     Date/Time   : 2016-08-20, 08:11, # CodeGen: 5
**     Contents    :
**         FLEXCAN_DRV_SetBitrate              - flexcan_status_t FLEXCAN_DRV_SetBitrate(uint8_t...
**         FLEXCAN_DRV_GetBitrate              - flexcan_status_t FLEXCAN_DRV_GetBitrate(uint8_t...
**         FLEXCAN_DRV_SetRxMaskType           - void FLEXCAN_DRV_SetRxMaskType(uint8_t instance,flexcan_rx_mask_type_t type);
**         FLEXCAN_DRV_SetRxFifoGlobalMask     - flexcan_status_t FLEXCAN_DRV_SetRxFifoGlobalMask(uint8_t...
**         FLEXCAN_DRV_SetRxMbGlobalMask       - flexcan_status_t FLEXCAN_DRV_SetRxMbGlobalMask(uint8_t...
**         FLEXCAN_DRV_SetRxIndividualMask     - flexcan_status_t FLEXCAN_DRV_SetRxIndividualMask(uint8_t...
**         FLEXCAN_DRV_Init                    - flexcan_status_t FLEXCAN_DRV_Init(uint32_t instance,flexcan_state_t *...
**         FLEXCAN_DRV_Deinit                  - uint32_t FLEXCAN_DRV_Deinit(uint8_t instance);
**         FLEXCAN_DRV_ConfigTxMb              - flexcan_status_t FLEXCAN_DRV_ConfigTxMb(uint8_t instance,uint32_t...
**         FLEXCAN_DRV_SendBlocking            - flexcan_status_t FLEXCAN_DRV_SendBlocking(uint8_t instance,uint32_t...
**         FLEXCAN_DRV_Send                    - flexcan_status_t FLEXCAN_DRV_Send(uint8_t instance,uint32_t...
**         FLEXCAN_DRV_ConfigRxMb              - flexcan_status_t FLEXCAN_DRV_ConfigRxMb(uint8_t instance,uint32_t...
**         FLEXCAN_DRV_ConfigRxFifo            - flexcan_status_t FLEXCAN_DRV_ConfigRxFifo(uint8_t...
**         FLEXCAN_DRV_RxMessageBufferBlocking - flexcan_status_t FLEXCAN_DRV_RxMessageBufferBlocking(uint8_t...
**         FLEXCAN_DRV_RxMessageBuffer         - flexcan_status_t FLEXCAN_DRV_RxMessageBuffer(uint8_t instance,uint32_t...
**         FLEXCAN_DRV_RxFifoBlocking          - flexcan_status_t FLEXCAN_DRV_RxFifoBlocking(uint8_t...
**         FLEXCAN_DRV_RxFifo                  - flexcan_status_t FLEXCAN_DRV_RxFifo(uint8_t instance,flexcan_msgbuff_t * data);
**         FLEXCAN_DRV_IRQHandler              - void FLEXCAN_DRV_IRQHandler(uint8_t instance);
**         FLEXCAN_DRV_GetTransmitStatus       - flexcan_status_t FLEXCAN_DRV_GetTransmitStatus(uint32_t instance);
**         FLEXCAN_DRV_GetReceiveStatus        - flexcan_status_t FLEXCAN_DRV_GetReceiveStatus(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file canCom1.h
** @version 01.00
*/         
/*!
**  @addtogroup canCom1_module canCom1 module documentation
**  @{
*/         
#ifndef __canCom1_H
#define __canCom1_H
/* MODULE canCom1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define FSL_CANCOM1 (0U)
/*! @brief Driver state structure which holds driver runtime data */
extern flexcan_state_t canCom1_State; 
/*! @brief Common configuration declaration */
extern const flexcan_user_config_t canCom1_InitConfig0;
    

#endif
/* ifndef __canCom1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

